### ISSUE TITLE
Documentation Discrepancy - Root Grid Padding iOS/Android

### ISSUE THREAD

**Issue by appsure** [brminnick/HelloMauiMarkup#23]
Seems the code is now using On<iOS>().SetUseSafeArea(shouldUseSafeArea) in the BaseContentPage but in the README you're using:
Padding = Device.RuntimePlatform switch
    {
        Device.iOS => new Thickness(30, 60, 30, 30),
        _ => new Thickness(30)
    },
Just a heads up.

**Comment by brminnick** [comment]
Thanks! Yea, the README is intended for a quick glance + copy/paste. 

I recommend using `On().SetUseSafeArea(shouldUseSafeArea)` in your apps like I do in the source code.
